# 1. Fortæl Spring vi bruger H2
spring.datasource.url=jdbc:h2:mem:beskyttelsesrumdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. slår H2 web-console til (til adgang via browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Vis SQL kommandoer i terminalen (til debugging)
spring.jpa.show-sql=true

# 4. JPA opretter tabellerne hver gang applikationen startes (frisk database)
spring.jpa.hibernate.ddl-auto=create-drop